repos:
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      exclude: ^test(s)?/  # keep in sync with .bandit file
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
    - id: mypy
      exclude: ^tests/  # keep in sync with mypy.ini
      additional_dependencies: [types-pyOpenSSL]
