repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
    - id: bandit
      exclude: ^test(s)?/  # keep in sync with .bandit file
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
    - id: mypy
      exclude: ^tests/  # keep in sync with mypy.ini
