name: macOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          brew update
          brew install swig
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run unit tests
        run: poetry run pytest -v

      - name: Build
        run: poetry build

      - name: Install from tar.gz
        run: |
          pip install dist/*.tar.gz
          ykman --version
          [[ -z "$(ykman --version | grep -E "not found|missing")" ]]
          pip uninstall yubikey-manager

      - name: Install from wheel
        run: |
          pip install dist/*.whl
          ykman --version
          [[ -z "$(ykman --version | grep -E "not found|missing")" ]]
          pip uninstall yubikey-manager
