name: Build a source package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq swig libpcsclite-dev
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run unit tests
        run: poetry run pytest

      - name: Create source package
        run: |
          poetry build
          mkdir artifacts
          export REF=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
          mv dist/yubikey-manager-*.tar.gz artifacts/yubikey-manager-$REF.tar.gz
          mv dist/yubikey_manager-*.whl artifacts/yubikey_manager-$REF.whl

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubikey-manager-source-package
          path: artifacts
