name: Ubuntu

on: [push, pull_request]

jobs:
  deb:
    runs-on: ubuntu-18.04
    name: Build .deb

    steps:
      - uses: actions/checkout@v2

      - name: Check Debian version
        run: |
          export PY_VER=$(awk '/__version__/{print $NF}' ykman/__init__.py | tr -d '"')
          export DEB_VER=$(dpkg-parsechangelog --show-field Version)
          case "$PY_VER" in
            *-dev*)
              if [[ ! $DEB_VER =~ "+git" ]]
              then
                echo "Debian package version mismatch, must contain +git!"
                exit 1
              fi
              ;;
            *)
              if [ $PY_VER != $DEB_VER ]
              then
                echo "Debian package version mismatch, expected $PY_VER!"
                exit 1
              fi
              ;;
          esac

      - name: Build .deb
        run: |
          sudo apt install -y devscripts equivs
          yes | sudo mk-build-deps -i debian/control
          debuild -us -uc
          mkdir dist
          mv ../yubikey-manager_* dist/

      - name: Install .deb
        run: |
          sudo dpkg -i dist/yubikey-manager_*.deb

      - name: Run CLI
        run: |
          ykman --version
          [[ -z "$(ykman --version | grep -E "not found|missing")" ]]

      - name: Upload Debian packages
        uses: actions/upload-artifact@v1
        with:
          name: python-deb-files
          path: dist
